"""Signature tests — golden vectors produced by the *client's own* JS code.

The expected strings below were generated by running the original
``electron/xfyun/sign.js`` algorithm under Node, so a regression in the Python
port is caught immediately.
"""

from __future__ import annotations

import unittest

from loomy2api import signer


class TestStringToSign(unittest.TestCase):
    def test_plain_body(self):
        expected = (
            "POST\n"
            "/login/account/getPuKey\n"
            "\n"
            "ZXFsDbtKIeoeelrBB+sO7g==\n"
            "application/json\n"
            "Sat, 26 Sep 2026 12:00:00 GMT\n"
            "11111111-2222-3333-4444-555555555555\n"
            "\n"
        )
        got = signer.string_to_sign(
            method="post", path="/login/account/getPuKey",
            body='{"base":{"appid":"GM3LOOMY"}}',
            date="Sat, 26 Sep 2026 12:00:00 GMT",
            nonce="11111111-2222-3333-4444-555555555555",
        )
        self.assertEqual(got, expected)

    def test_signature_matches_node(self):
        sig = signer.sign(
            secret="TEST_SECRET", method="POST",
            path="/login/account/getPuKey",
            body='{"base":{"appid":"GM3LOOMY"}}',
            date="Sat, 26 Sep 2026 12:00:00 GMT",
            nonce="11111111-2222-3333-4444-555555555555",
        )
        self.assertEqual(sig, "hu4CwF8SGwW9+0aCwfU7idd7gho=")

    def test_query_escaping_and_custom_headers(self):
        expected = (
            "POST\n"
            "/login/phone/checkCode\n"
            "a=1%202&b=x%28y%29\n"
            "\n"
            "application/json\n"
            "Sat, 26 Sep 2026 12:00:00 GMT\n"
            "nonce-2\n"
            "x-other;x-test\n"
            "x-other:2\n"
            "x-test:v1"
        )
        got = signer.string_to_sign(
            method="POST", path="/login/phone/checkCode/",
            query={"a": "1 2", "b": "x(y)"}, body="",
            date="Sat, 26 Sep 2026 12:00:00 GMT", nonce="nonce-2",
            custom_headers={"X-Test": " v1 ", "x-other": "2"},
        )
        self.assertEqual(got, expected)
        self.assertEqual(
            signer.sign(secret="TEST_SECRET", method="POST",
                        path="/login/phone/checkCode/",
                        query={"a": "1 2", "b": "x(y)"}, body="",
                        date="Sat, 26 Sep 2026 12:00:00 GMT", nonce="nonce-2",
                        custom_headers={"X-Test": " v1 ", "x-other": "2"}),
            "53bKaJEgHxiy8d7lYUMWFhmLtY0=")

    def test_trailing_slash_is_stripped(self):
        a = signer.string_to_sign(method="POST", path="/a/b/", date="d", nonce="n")
        b = signer.string_to_sign(method="POST", path="/a/b", date="d", nonce="n")
        self.assertEqual(a, b)

    def test_empty_body_has_empty_md5(self):
        self.assertEqual(signer.content_md5(""), "")
        self.assertEqual(signer.content_md5("abc"), "kAFQmDzST7DWlj99KOF/cg==")


class TestHeaders(unittest.TestCase):
    def test_build_headers_shape(self):
        headers = signer.build_headers(
            "AKID", "SECRET", method="POST", path="/login/account/getPuKey",
            body='{"x":1}')
        self.assertTrue(headers["Authorization"].startswith("account AKID:"))
        self.assertIn("Date", headers)
        self.assertIn("Nonce", headers)
        self.assertEqual(headers["Content-Type"], "application/json")
        self.assertIn("Content-MD5", headers)

    def test_no_md5_without_body(self):
        headers = signer.build_headers("AKID", "SECRET", method="POST",
                                       path="/x", body="")
        self.assertNotIn("Content-MD5", headers)


if __name__ == "__main__":
    unittest.main()
